apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-14T11:40:15Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "15073"
  uid: 362e0a77-3756-4707-af90-0ea296bc8209
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.244.216
  clusterIPs:
  - 10.101.244.216
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31558
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
